### ISSUE TITLE
Cannot use with webpack

### ISSUE THREAD

**Issue by codingedgar** [Effect-TS/match#172]
Not sure if this is related but if you try:

`yarn add -E @effect/data@0.17.1 @effect/io@0.38.0 @effect/schema@0.33.0 @effect/match`

or

`npm i --save-exact @effect/data@0.17.1 @effect/io@0.38.0 @effect/schema@0.33.0 @effect/match && npm run postinstall`

in

`https://github.com/electron-react-boilerplate/electron-react-boilerplate` 

Throws:

`ERROR in dll renderer renderer[0]
Module not found: Error: Package path . is not exported from package /electron-react-boilerplate/node_modules/@effect/data (see exports field in /electron-react-boilerplate/node_modules/@effect/data/package.json)`

I was trying to use @effect/match but couldn't figure out how to install it

also posted here: https://github.com/Effect-TS/data/issues/450#issuecomment-1682641595

**Comment by wesselvdv** [comment]
I use webpack, but I don't see this issue at all.

**Comment by codingedgar** [comment]
> I use webpack, but I don't see this issue at all.

might have been solved downstream (?)

i'll close the issue since I do not actively use the package anymore (i'll wait till v1 to try again)
